# These are supported funding model platforms

github: [openpaper-ai]
# patreon: # Replace with your Patreon page
# open_collective: # Replace with your Open Collective page
# ko_fi: # Replace with your Ko-fi page
# tidelift: # Replace with your Tidelift page
# community_bridge: # Replace with your Community Bridge page
# liberapay: # Replace with your Liberapay page
# issuehunt: # Replace with your IssueHunt page
# otechie: # Replace with your Otechie page
# custom: # Replace with your custom URLs
